// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/room/:roomCode": {
    params: {
      "roomCode": string;
    };
  };
  "/noServerConnection": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/room/:roomCode" | "/noServerConnection";
  };
  "./routes/layout.tsx": {
    id: "routes/layout";
    page: "/" | "/room/:roomCode";
  };
  "./routes/main_menu.tsx": {
    id: "routes/main_menu";
    page: "/";
  };
  "./routes/room.tsx": {
    id: "routes/room";
    page: "/room/:roomCode";
  };
  "./routes/no_server_connection.tsx": {
    id: "routes/no_server_connection";
    page: "/noServerConnection";
  };
};